apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: distribution
type: Opaque
data:
  secret: TWpRMFlUTTRaR1JqT1dGbE5UQmlZV1ZsTmpsaE5UQTBZbVF6T0dJM05qQTFPR1ZpWmpNeE1qWmpOak5oTkRJNVlXRXpPRE5tTXpFeFpqRTFNMlZsWWpFd04yUmtaalk1TmpBM01qTXdORFF4TTJJeVpqZ3dNemN6WWpkbE1XTXdORGRrTVRsbE9XVm1OVGc1T0RaaVlUbGhaams0T0RKbE5HVXpObVF4T1RNPQ==
