apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mysql
  namespace: distribution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mysql
  template:
    metadata:
      labels:
        app: k8s-mysql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image:  mysql:5.7.26
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: test
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mysql
  namespace: distribution
spec:
  selector:
    app: k8s-mysql
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31306

