apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-weave
  namespace: weave
spec:
  rules:
  - host: k8s.weave
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
